variables:
- group: VariableGroup
- name: global_variable
  value: value_global-overwrite_1 
- name: directory_include
  value: ./include
- template: ${{ variables.directory_include }}/variables.yml

trigger:
- master


jobs:
- job: jobD
  variables:
    testResultsFile: "$(Agent.WorkFolder)/testresults.xml"
  steps:
    - task: AzurePowerShell@4
      displayName: Run Pester...
      inputs:
        azurePowerShellVersion: LatestVersion
        azureSubscription: "rg-playground-carth-service-connection"
        ScriptType: InlineScript
        Inline: |
            $PSVersionTable

            Install-Module -Name Pester -Force -ErrorAction Stop

            $PesterSettings = @{
              Script = @{
                Path = "$(System.DefaultWorkingDirectory)/tests/pester.tests.ps1"
                Parameters = @{
                  parameter1 = 'value of parameter1'
                  parameter2 = 'value of parameter2'
                }
              }
              OutputFile = "$(testResultsFile)"
              OutputFormat = "NUnitXml"
              EnableExit = $true
              Verbose = $true
            }

            Invoke-Pester @PesterSettings
    
    - task: PublishTestResults@2
      displayName: Publish Pester tests results
      inputs:
        testResultsFormat: NUnit
        testResultsFiles: $(testResultsFile)
