variables:
- group: VariableGroup
- name: global_variable
  value: value_global-overwrite_1 
- name: directory_include
  value: ./include
- template: ${{ variables.directory_include }}/variables.yml

pool: 
  name: carth-pool

trigger:
  batch: true
  branches:
    include:
    - master

jobs:
- template: simple-param.yml
  parameters:
    title: "This is the ROOT title"
    pool:
      name: carth-pool

- job: jobB
  dependsOn: [jobA]
  steps:
  - template: simple-param-2.yml
    parameters:
      yesNo: true
  - template: simple-param-2.yml
    parameters:
      yesNo: false
      title: "This is the root title"