trigger:
  batch: true
  branches:
    include:
    - master

jobs:
- job: RunCustomTask
  pool: 
    vmImage: vs2017-win2016
  steps:
  - checkout: none

  - task: Carth.build-release-task.HelloBuildTask.CarthTask@0
    inputs:
      name: 'My Name CarthTask@0'
      sampleString: 'This is a string CarthTask@0'
      sampleNumber: '0'
      sampleBoolean: true
      action: 'choice2'

  - task: Carth.build-release-task.HelloBuildTask.CarthTask@1
    inputs:
      azureSubscription: 'rg-playground-carth-service-connection'

  - script: echo output "=" $(outputFromCustomTask)