trigger:
  batch: true
  branches:
    include:
    - master


jobs:
- job: Keyvault
  steps:
#  - task: AzureKeyVault@1
#    inputs:
#        azureSubscription: 'rg-playground-carth-service-connection'
#        KeyVaultName: 'kv-carth'
#        SecretsFilter: '*'
#  
#  - pwsh: |
#      Write-Host "Values from Keyvault kv-carth"
#      Write-Host $(secret2)

    - task: buildAndReleaseTask@0
      inputs:
        samplestring: 'fqfgsdfsd'