trigger:
- master

stages:
- stage: Stage 1
  pool:
    vmImage: 'ubuntu-latest'
  jobs:
    - job: Job_1_1
      steps:
        - script: echo from Job 1
          displayName: 'Run job1 script'
    - job: Job_1_2
      steps:
        - script: echo from Job 2
          displayName: 'Run job 2 script'
- stage: Stage 2
  pool:
    vmImage: 'ubuntu-latest'
  jobs:
    - job: Job_2_1
      steps:
        - script: echo from Job 1
          displayName: 'Run job1 script'
    - job: Job_2_2
      steps:
        - script: echo from Job 2
          displayName: 'Run job 2 script'

- stage: Stage 3
  pool:
    vmImage: 'ubuntu-latest'
  jobs:
    - job: Job 
      steps:
        - task: PowerShell@2
          inputs:
            filePath: './script/test.ps1'