trigger:
  batch: true
  branches:
    include:
    - master


jobs:
- job: Keyvault
  steps:
  - task: AzureKeyVault@1
    inputs:
        azureSubscription: 'rg-playground-carth-service-connection'
        KeyVaultName: 'kv-carth'
        SecretsFilter: '*'
  