name: TestExtension-$(Build.BuildId)

trigger:
  batch: true
  branches:
    include:
    - master

jobs:
- job: RunCustomTask
  pool: 
    vmImage: windows-latest
  steps:
  - checkout: none

  - task: CarthTask@0
    inputs:
      name: 'My Name CarthTask@0'
      sampleString: 'This is a string CarthTask@0'
      sampleNumber: '0'
      sampleBoolean: true
      action: 'choice2'

  - task: CarthTask@1
    condition: succeededOrFailed()
    inputs:
      azureSubscription: 'rg-playground-carth-service-connection'

  - script: echo output "=" $(outputFromCustomTask)