variables:
- group: VariableGroup
- name: global_variable
  value: value_global-overwrite_1 
- name: directory_include
  value: ./include
- template: ${{ variables.directory_include }}/variables.yml

trigger:
  batch: true
  branches:
    include:
    - master

jobs:

- job: jobA   
  steps:
  - template: simple-param.yml
    displayName: "Simple param - default"

- job: jobB
  dependsOn: [jobA]
  steps:
  - template: simple-param.yml
    displayName: "Simple param - true"
    parameters:
      yesNo: true
  - template: simple-param.yml
    displayName: "Simple param - false"
    parameters:
      yesNo: false