trigger:
  batch: true
  branches:
    include:
    - master


jobs:
- job: RunCustomTask
  pool: 
    vmImage: vs2017-win2016
  steps:
  - task: HelloWorld@0
    inputs:
      name: 'My Name'
      sampleString: 'This is a string'
      sampleNumber: '0'
      sampleBoolean: true
      ressourceGroupName: 'Dummy RessourceGroupName'
      action: 'choice2'