trigger:
- master

stages:
- stage: Stage_1
  jobs:
    - job: Job_1_1
      steps:
        - script: echo from Job 1
          displayName: 'Run job1 script'
        - script: echo from Job 2
          displayName: 'Run job 2 script'

- stage: Stage_2_1
  dependsOn: [Stage_1]
  jobs:
    - job: Job_2_1_1
      steps:
        - script: echo from Job 1
          displayName: 'Run job1 script'
        - script: echo from Job 2
          displayName: 'Run job 2 script'

- stage: Stage_2_2
  dependsOn: [Stage_1]
  jobs:
    - job: Job_2_2_1
      steps:
        - script: echo from Job 1
          displayName: 'Run job1 script'
        - script: echo from Job 2
          displayName: 'Run job 2 script'

- stage: Stage_3
  dependsOn: [Stage_2_1, Stage_2_2]
  jobs:
    - job: Job 
      steps:
        - task: PowerShell@2
          inputs:
            filePath: './script/test.ps1'