variables:
- template: variables.yml
- name: global_variable
  value: value_global-overwrite_1 

trigger:
- master

jobs:
- job: job1
  variables:
    job_variable1: value_job1    # this is only available in job1
  steps:
  - powershell: |
      Write-Host "Global variable = $(global_variable)"
      Write-Host "Job variable = $(job_variable1)"
      Write-Host "Job variable = $(JOB_VARIABLE1)"

- job: job2
  dependsOn: [job1]
  variables:
    job_variable2: value_job2    # this is only available in job2
  steps:
  - powershell: |
      Write-Host "Global variable = $(global_variable)"
      Write-Host "Job variable = $(job_variable2)"
      Write-Host "Global variable = $(GLOBAL_VARIABLE)"