trigger:
  batch: true
  branches:
    include:
    - master


jobs:
- job: RunCustomTask
  pool: 
    vmImage: vs2017-win2016
  steps:
  - task: buildAndReleaseTask@0
    inputs:
      sampleString: 'This is my string'
      sampleNumber: '659'
      sampleBoolean: false