name: TestExtension-$(Build.BuildId)

trigger:
  batch: true
  branches:
    include:
    - master

pool: 
  vmImage: windows-latest

jobs:
- job: RunCustomTask
  steps:
  - checkout: none
  - task: CarthTask@1
    name: CarthTaskName
    inputs:
      azureSubscription: 'rg-playground-carth-service-connection'
  - script: |
        echo output1 2 = $(CarthTaskName.outputFromCustomTaskV1)
        echo exampleName2 = $(CarthTaskName.exampleName)

- job: OtherTask
  dependsOn: RunCustomTask
  variables:
    var1FromCarthTask : $[ dependencies.RunCustomTask.outputs['CarthTaskName.outputFromCustomTaskV1'] ]
    var2FromCarthTask : $[ dependencies.RunCustomTask.outputs['CarthTaskName.exampleName'] ]
  steps:
  - checkout: none
  - script: |
        echo var1FromCarthTaskv1 = $(var1FromCarthTask)
        echo var2FromCarthTaskv1 = $(var2FromCarthTask)
  
    