trigger:
  batch: true
  branches:
    include:
    - master

jobs:
- job: RunCustomTask
  pool: 
    vmImage: vs2017-win2016
  steps:
  - checkout: none
  - pwsh: |
      Write-Host "aVariable : " $env:aVariable
      Write-Host "mysecret : " $env:mysecret
  - task: InstallAzureDevOpsExtension@2
    inputs:
      connectTo: 'VsTeam'
      connectedServiceName: 'Marketplace service connection'
      method: 'id'
      publisherId: 'Carth'
      extensionId: 'build-release-task'
      accounts: 'https://dev.azure.com/thierrycarels0265/'

  - task: CarthTask@0
    inputs:
      name: 'My Name CarthTask@0'
      sampleString: 'This is a string CarthTask@0'
      sampleNumber: '0'
      sampleBoolean: true
      action: 'choice2'

  - task: CarthTask@1
    inputs:
      name: 'My Name CarthTask@1'
      sampleString: 'This is a string CarthTask@1'
      sampleNumber: '1'
      sampleBoolean: false
      action: 'choice1'

  - script: echo output "=" $(outputFromCustomTask)