name: TestExtension-$(Build.BuildId)

trigger: none

variables:
  myCollection:
  - key: myKey1
    value: my value 1
  - key: myKey2
    value: my value 2

jobs:
- job: Loop
  steps:
  - checkout: none
  - template: loop-pipeline.yml
    parameters:
      param: [ "a", "b", "c"]