name: TestExtension-$(Build.BuildId)

trigger: none

jobs:
- job: Loop
  steps:
  - checkout: none
  - template: loop-pipeline.yml
    parameters:
      param: [ "a", "b", "c"]

  - task: AzureCLI@2
    inputs:
      azureSubscription: 'rg-playground-carth-service-connection'
      scriptType: 'pscore'
      scriptLocation: 'inlineScript'
      inlineScript: |
        az artificats download
        az blablaba