parameters:
- name: yesNo
  type: boolean
  default: false
- name: title
  type: string
  default: "default name"

jobs:
- job:
  steps:
    - template: simple-param-2.yml
      parameters:
        yesNo: true
    - template: simple-param.yml
      parameters:
        yesNo: $${{ parameters.yesNo }}
        title: $${{ parameters.title }}
